### ISSUE TITLE
Make R support more flexible

### ISSUE THREAD

**Issue by jmjwozniak** [swift-lang/swift-t#100]
Does not currently support APT package R with install.packages(Rcpp,RInside)
Also reported by @ncollier

**Comment by ncollier** [comment]
Not sure if this is the same thing but the autodetect_rinside_rcpp branch that I pushed co trains fixes to discover where R installs rinside etc and check those paths.

**Comment by jmjwozniak** [comment]
Nice- I think this works.  The Swift/T guide is updated.

**Comment by jmjwozniak** [comment]
Nice- I think this works.  The Swift/T guide is updated.

**Comment by jmjwozniak** [comment]
I tested this on Linux with R from APT and R from source.  @ncollier , does this work for you on your Mac?

**Comment by ncollier** [comment]
Yes. Jonathan tested it was well and his R and python installs are different than mine as well.

**Comment by jmjwozniak** [comment]
Great, thanks!
