### ISSUE TITLE
In Makefile, CP_ARGS causes CP_PARENTS to fail on OSX

### ISSUE THREAD

**Issue by ncollier** [swift-lang/swift-t#106]
With master, commit 03b7e471d29d3304158d9d86bf0893ace56f144f.

Under OSX, CP_PARENTS resolves to maint/cp-parents.sh, and CP_ARGS is -vf. Makefile.in contains several commands that use both (lines 788 and 790 for example).

```
$(E) $(CP_PARENTS) $(CP_ARGS) $(SCRIPTS) $(INSTALL_TOP)
```

However, passing -vf (i.e. $(CP_ARGS)) to cp-parents.sh causes the copy to fail as "-vf" becomes the file to copy for some reason.

```
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
cp-parents.sh: failed on command:
 cp -vf /Users/nick/sfw/swift-t-git/turbine/-vf

usage: cp-parents.sh ARGS SRC/FILE DEST
Copies SRC/FILE to DEST/SRC/FILE
ARGS must start with dash and are passed to cp
Emulates GNU's cp --parents
```

"CP_ARGS=" allows the copy to succeed.

**Comment by jmjwozniak** [comment]
The whole point of this script was to work on the Mac- let me try it on Frisbee...
