### ISSUE TITLE
simplify configuring python support

### ISSUE THREAD

**Issue by bd4** [swift-lang/swift-t#110]
Modern python (at least since 2.7) has a script called `python-config` that provides all the paths necessary for building embedded interpreter C integration code. This can be supported via a new configure option (to avoid breaking any existing build scripts or exotic python installs):

```
# use python-config in path
./configure --with-python-config

# use specific python-config exe
./configure --with-python-config=/path/to/pythonX.Y-config
```

This could also be bolted on to the existing `--with-python`, instead of as a separate option. See gdb for an example of kitchen sync python build configuration:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=gdb/configure.ac;h=50f6f592ba677ce8e0b3cd36b0df607ace03efe8;hb=HEAD#l728

**Comment by bd4** [comment]
Interestingly gdb includes a copy of python-config.py from 2.7, and calls that using users specified python exe. Presumably this allows supporting versions prior to 2.7 that don't include a `python-config`, but seems like overkill for turbine, which already has manual config to support older versions.

**Comment by jmjwozniak** [comment]
Can we close this?

**Comment by bd4** [comment]
Yes, `--with-python-exe` is working.
