### ISSUE TITLE
Doc: MPE logging

### ISSUE THREAD

**Issue by zo0z** [swift-lang/swift-t#115]
The Swift/T User Guide , and Developer guide are a bit obscure about how this functionality can be triggered. What is evident from the code is that they require Swift/T to be built with MPE enabled, but unfortunately, simply setting `ENABLE_MPE=1 `in the `<swift/T dir>/dev/build/swift-t-settings.sh` is not sufficient to trigger the functionality, and I was only able to enable it in my system by manually building Swift/T from source following these steps:

*0.1 Prerequisites: Installing an MPI client:*
I’m using the default MPICH client that came with my machine (Ubuntu 16.04), and it is already in the default search path.

_0.2 Prerequisites: Installing MPE library:_
This starts by downloading the library, for example from the official site
Installing from source is ideally straight forward, except that one also needs to generate a shared library file `libmpe.so`, which the Swift/T installer expects to find in the` mpe_installation_dir/lib`.
The final command looks something like:

```
./configure CC=mpicc F77=mpifort –prefix=<desired_mpe_installaion_dir> MPI_LIBS=-lpthread –enable-PIC
make && make install
make installcheck  # 4 yeses is what you are looking for!
export PATH=$PATH:<mpe_installation_dir/bin> # or change your ~/.profile or ~/.bachrc - depending on your system
```

*Notes about the configuration parameters:*

- `CC and F77 `are program to compile MPI C programs and MPI fortran programs, and they are mandatory parameters when building MPE from source. I’m working with default mpicc, so these are fine
-  `MPI_LIBS=-lpthread`: this parameter is an MPI requirement. On my machine, regular MPI programs do not compile successfully without this library. Therefore, I needed to include it in the MPE build process as well
- `--enable-PIC` here was the deal breaker. Without it, I couldn’t go on to building a shared library (libmpe.so), which the Swift/T installer expected to find in `<installation_path>/lib`.

    Once MPE is installed properly, you will need to run code similar to this: https://trac.mpich.org/projects/mpich/ticket/1104 to create the shared library (.so) file. This is a work around, as MPE does not support shared libraries, even if you configure with `–enable-shared`

With this done successfully, the MPE_installation directory will need to be passed to each consequent program in Swift/T which is explained below

1. First, you will need to untar the package (or clone this [repo](https://github.com/swift-lang/swift-t) somewhere. Note that all the location references below are originating from inside this untarred/cloned directory.Swift/T is actually the sum of 4 components, so its manual build is really a process of building each component on its own. These components are C-utils, ADLB library, Turbine and STC. 

> Disclaimer: This is how it worked for my machine, and I’m not sure if it would work on other systems.

One global note for each constituent application is that I’m installing them all within some parent directory (will call it `swift-t_installation_dir`), and then a sub-directory that corresponds to the library name. In other words, for each component, I’m passing a parameter: `--prefix=swift/library_name{c-utils|lb|turbine|stc}`. This makes things consistent with what would happen if installation was done automatically, but more importantly, it also makes it easier to notice the relations between libraries (which is very desirable in this case)

```
sudo wget http://swift-lang.github.io/swift-t/downloads/swift-t-1.2.tar.gz
sudo tar -xvzf swift-t-1.2.tar.gz 
cd swift-t-1.2/

# and for each library, I needed to  ./configure –help|less to get an idea for how to proceed
```

_1. For c-utils: This was straight forward:_
```
cd c-utils/code/
export CC=mpicc
mpichversion #To check the installed mpi version, mine is version 3.2
MPI_VERSION=3 #In case you were working with 
MPE_INSTALL=<mpe_installation_dir>
ENABLE_MPE=1
./configure –prefix=<swift-t_installation_dir/c-utils> 
make
make install
```

_2. For ADLB library (lb)_
```
cd ../../lb/code/
export CFLAGS=-mpilog
export LDFLAGS="-L/<mpe_installation_dir/lib>/ -lmpe -Wl,-rpath -Wl,/<mpe_installation_dir>/lib"
./configure --with-mpe=<mpe_installation_dir> --with-c-utils=<swift-t_installation_dir/c-utils> --prefix=<swift-t_installation_dir/lb> CC=mpecc
make
make install
```

*Side note:*
Looking at my history, I’m concluding this process needed making some changes to the `/lb/code/configure` file. I don’t particularly remember what I changed there, but I note the following entries in the installation process, so below I list such suggestive commands:
```
grep -R "lb/code" *  
# This command was issued because configuration failed with an error message complaining about c-utils installation, claiming it is installed in 0/lb/code – or so I recall. Since it was correctly passed to configure with the correct  --with-c-utils argument, this meant looking at the configure file itself. I think I put 4527 as: location=${SOFTWARE}/c-utils, but I’m not sure

grep -R mpilog *
 #Configuring was successful at last, but then the make failed due to unrecognized mpilog library needed. The problem had to do with the LDFLAGS environment variable, so it was changed. This was noted from an exchange between code Swift/T developers starting at line 4410, that has a worrying remark _“I cannot figure this out”_. This worked in my system, and I’m not sure it will work on other systems, so some documentation is definitely needed here
```

_3. For turbine_
```
unset LDFLAGS
unset CFLAGS
./configure –prefix=<swift-t_installation_dir/turbine> --with-c-utils=<swift-t_installation_dir/c-utils> --with-mpe=<mpe_installation_dir> --with-adlb=<swift-t_installation_dir/lb> CC=mpicc
# I think I had to change something in the configure file, Probably at line 5344: USE_MPE=$with_mpe.  This is really a work around, that did the job on my system for this particular use case
make
make install
```

_4. For STC_
```
cd ../../stc/code
ant install -Ddist.dir=<swift-t_installation_dir/stc> -Dturbine.home=<swift-t_installation_dir/turbine>
```

_5. To check it all worked:_
```
cd <swift-t_installation_dir/turbine/bin>
./turbine -v

cd <swift-t_installation_dir/stc/bin>
./stc
./swift-t_installation_dir -v
```

**Comment by jmjwozniak** [comment]
Thanks for this detailed report!  I will try to integrate these notes into the Swift/T documentation.

**Comment by jmjwozniak** [comment]
Ok @zo0z , I merged your docs in here: http://swift-lang.github.io/swift-t/guide.html#mpe

**Comment by jmjwozniak** [comment]
I posted the tools and some initial docs here: https://github.com/swift-lang/swift-t/tree/master/mpe

**Comment by jmjwozniak** [comment]
I am going to close this but feel free to reopen or add new issues for follow-up questions.

**Comment by zo0z** [comment]
Thank you for providing these functions and documentation. This is very helpful indeed. 

I have a few follow up comments and questions, and I'm hoping to get some insights from your side as well...
```
```
### Side comment:
The C versions of the functions hosted in https://github.com/swift-lang/swift-t/tree/master/mpe
worked very well on my system (with the textual clog2 file as input), but I couldn't get the tcl version to work with either log file format (binary or textual). 
Looking a bit closely though, there is a call to the `read_defns` procedure which calls the transformation program: as in: `set fd [ open "|clog2_print $input_log" ]`, which would suggest that the tcl scripts accept binary log files . This partially works, but then provoking any of the tcl scripts with `adlb.clog2` as input triggers an error message that complains about the format of of the log file lines that is similar to the one below:
```
error in line 1: ts=0.049618 icomm=0 rank=0 thd=0 type=bare et=0
key "0" not known in dictionary
    while executing
"dict get $IDs $et "
    (procedure "process_line" line 24)
    invoked from within
"process_line $line "
```
The said line 1 above actually refers to one of the lines present in the input log file itself `adlb.clog2` , (but it is not the first line  in it per say).

  For some reason, I thought there is a problem with read_defns function initially, so I removed the pipe from all the open function calls, and directly passed the textual log file `adlb.clog2.txt`. Strangely however, in this case, the error message was still similar to the one above (except that it refers to a different key not being present in the dictionary). I had to stop debugging in the later case though, as the C-functions did the job very well anyway; and thought to just report back the above
 
```
```
### The question:
Besides these, I'm more interested in having the log file include a reference to app function calls, as it would be really useful to know where and how each app is being used and so on. Looking at the code (and the output from `list-events.x`), I'm concluding only solo events are reported in the log (in addition to other ADLB calls); and this is achieved via the standard library `metadata` function. This gives an entry named `metadata` in the log file, but is not really helpful in drawing much insight about pipeline run details.  Therefore, my first question is: _Is there a reason why only solo events are currently implemented, or am I missing some point here?_

My thinking to add more details is to instrument the MPE log, by specifying the apps start and end time as events and betwen them as states, and then proceed. In a typical C-program, this would involve calls to the functions below:
```
int MPE_Init_log(); // Initialize MPE logging
int MPE_Log_get_event_number(); //Obtain an event’s ID
int MPE_Describe_state(int start, int end, char name, charcolor); //Describe a state
int MPE_Start_log(int event, int intdata, char *chardata); // Start logging 
int MPE_Log_event(int event, int intdata, char *chardata); //Log the given event of the state
int MPE_Stop_log(void); // Stop logging a certain event
int MPE_Finish_log(char *logfilename); // Close the log, and write to the logfilename
```
But, given the wrapper functions defined in the `mpe` namespace, I think it is possible to make use of the mapping below between swift/t functions (to the left) and c functions (to the right): 

```
mpe::create_pair <symbol> => [ list start-ID stop-ID ]  ### MPE_Describe_state(event1a, event1b, "Broadcast", "red")
mpe::create_solo <symbol> => ID ### MPE_Log_get_event_number();
mpe::log <event-ID> [<message>] ### MPE_Log_event(event1a, 0, "start broadcast");
```


_Would this be a reasonable way to proceed? _ I really appreciate any kind of pointer you would be able to provide.

Thank you,
Azza
