### ISSUE TITLE
File variable not assigned

### ISSUE THREAD

**Issue by bnikolic** [swift-lang/swift-t#128]
STC issues error:
"Variable usage error. Variable o never written and is read on some code paths"
For file variables used inside a non-app function. However as an unmapped file variable is automatically created this is sometimes too strict. Example:

> 
> /* -*- mode: c; -*- */
> // Question on file variables used in non-app functions 
> 
> import python;
> 
> // This compiles
> app (file o) apptouch()
> {
>   "touch" o;
> }
> 
> // This does not compile
> (file o) pythontouch()
> {
>   python("from subprocess import call; call(['touch', '%s']);" % filename(o));
> }

**Comment by jmjwozniak** [comment]
I think this is a matter of documentation.

**Comment by bnikolic** [comment]
The issue is that the Python command is what creates the file and since it is not in an "app" function STC does not know that it has been created. The work around I have is to create a noop "app" function but it is not clear. See the code below:

```
/* -*- mode: c; -*- */
/* Question on file variables used in app functions */

import python;

app (file o) noop()
{
  ":" o;
}

// This compiles
app (file o) apptouch()
{
  "touch" o;
}

// This does not compile
(file o) pythontouch()
{
  // File a is declared but not filled
  file a;
  python("from subprocess import call; call(['touch', '%s']);" % filename(a));
  o=a;
}


// This compile, a workaround
(file o) pythontouchwnoop()
{
  o=noop();
  python("from subprocess import call; call(['touch', '%s']);" % filename(o));
}



```

**Comment by jmjwozniak** [comment]
There is a touch() function in the unix module you can use: http://swift-lang.github.io/swift-t/guide.html#library_unix

Using write("") is a faster way to create an empty file.  

Are you just trying to get a temporary file from Swift, process it with Python, and return it?

**Comment by bnikolic** [comment]
I have a Python application (with lots of native code) that operates on
files (often bigger than available memory).  In typical usage there are
one or more input files and an output file, e.g. in Python

> importverylargedataset(["inputfile.hdf5"], "outputfile.fits")

but that does not seem to affect the issue here so I simplified to just
a touch operation.

The unmapped temporary created by SWIFT/T will be written to by this
Python function. So neither touch() nor write("") are really needed,
just a way to tell the compiler that the python function will write to
the output file.

**Comment by jmjwozniak** [comment]
I just added a mktemp() function.  See new STC test 5612-mktemp.swift for example usage.
