### ISSUE TITLE
Various tokenization and quoting bugs in turbine::sync_exec

### ISSUE THREAD

**Issue by timarmstrong** [swift-lang/swift-t#13]
The basic cause is that we're calling out to system, which requires taking our nicely tokenized args, munging them into a single string, and hoping that system will re-tokenize the string back into the original form.  This is possible if you escape the string correctly (turbine::sync_exec doesn't).

Test 6392 is one example where this breaks.  There will be others.

We could avoid that whole mess if we just call execvp() or similar with our tokenized args instead  http://pubs.opengroup.org/onlinepubs/009695399/functions/exec.html

**Comment by jmjwozniak** [comment]
Good point.  I was trying to stay compatible with Tcl's exec but that might be out.  I'm hoping to stay with system() as I don't want to implement redirection.

**Comment by timarmstrong** [comment]
I'm looking at how Tcl's exec is implemented. 

There are some functions there that may be useful.  Tcl_OpenCommandChannel will create a subprocess given a set of args, and will process exec-style redirects.  ttps://www.tcl.tk/man/tcl8.6/TclLib/OpenFileChnl.htm

What was the reason we didn't want to use exec again?  Was it some additional features that we didn't want?

**Comment by jmjwozniak** [comment]
There was some bug on the Cray.   Tcl's exec would fail once every few thousand invocations.

**Comment by jmjwozniak** [comment]
Using Tcl's library could trigger that bug again but is worth a try.

**Comment by timarmstrong** [comment]
Ahh I see.  That's a pain...

**Comment by timarmstrong** [comment]
I reimplemented this using fork/execvp/wait directly.  Implementing the redirection wasn't too bad since I only implemented the subset actually needed for Swift

See commit 461adc54c4a70e7cd528576348e20fef4ed3be6f

If you have a chance, it would be good to have a second pair of eyes on it.

**Comment by jmjwozniak** [comment]
Looks good as far as I can tell.  Adding a Turbine test was a good idea!

**Comment by timarmstrong** [comment]
Hopefully it avoids the cray bugs you saw.  What Tcl was doing to implement its exec was pretty complicated so I'm guessing the problem was somewhere in the details there.
