### ISSUE TITLE
Dataflow when using arrays of files

### ISSUE THREAD

**Issue by bnikolic** [swift-lang/swift-t#130]
When using file type objects in arrays the dataflow rules do not seem be be followed, i.e., operations on files commence before they have been created. Simplified illustration:
```
import unix;

(file o) bntouch()
{
   o=touch()=>
   trace("created", filename(o));
   
}

arraytest(file a[])
{
   wait(a)
   {
       trace("Wait finished");
   }
}

file c1=bntouch();
file c2=bntouch();
arraytest([c1, c2]);

```
Prints: 

```
race: Wait finished                                                                                                                                                                     
trace: created,/tmp/tcl_6wBGUP.turbine                                                                                                                                       
trace: created,/tmp/tcl_pTLVuC.turbine                                                                                                                                           

```

Am I missing something simple here?

**Comment by timarmstrong** [comment]
IIRC wait(A) {} just waits until all possible assignments to the top-level array have happened. wait deep (A) {} I think is needed to wait until all the contents of the array are assigned.

**Comment by bnikolic** [comment]
Many thanks for that, the larger application I am working on also seems to work with this. I see the deep modifier is mentioned in ./stc/tests/922-wait-deep.swift but no mention in the documentation as far as I can see. I'll see if I can prepare a patch for the docs

**Comment by bnikolic** [comment]
See  RP #131  for the doc fix
