### ISSUE TITLE
Spack: SWIG dependency not right

### ISSUE THREAD

**Issue by jmjwozniak** [swift-lang/swift-t#144]
@dorier: "When Spack tries to compile turbine, it doesn't find Swig. I had to run "spack install swig" then "spack load swig" and re-run "spack install stc"."  
@bd4 , do you have time to look at this?

**Comment by bd4** [comment]
I've run into this too, stc package is completely missing a swig dependency. @jmjwozniak is it both a runtime and build dependency, and which min version or range should it require?

**Comment by jmjwozniak** [comment]
It's both build and runtime.  We support all SWIG versions that I have tried, going back several years.

**Comment by bd4** [comment]
Current deps:

- excmutils: none
- adlbx: excmutils, mpi
- turbine: adlbx, tcl, zsh(type=run)
- stc: turbine, java, ant

I seem to remember hitting a missing zsh dependency as well - is turbine run really the only zsh dep? Is stc the only of the packages with the swig dep?

**Comment by jmjwozniak** [comment]
For Turbine, ZSH should also be build+run.  The SWIG dep is actually in Turbine.  STC could also depend on ZSH for type=run .

**Comment by bd4** [comment]
I submitted a pr: https://github.com/spack/spack/pull/6530

**Comment by jmjwozniak** [comment]
Should we close this when Spack merges your PR?

**Comment by jmjwozniak** [comment]
I think this is fixed now.
