### ISSUE TITLE
App retries

### ISSUE THREAD

**Issue by zo0z** [swift-lang/swift-t#149]
A Swif/t App may fail nondeterministically, and be tried to run in the same host and MPI rank using the `TURBINE_APP_RETRIES` directive.
It may be useful however to attempt to run the app in a different rank (in case one of the hosts is unavailable, or there is network issue or the like). This [pull request:](https://github.com/swift-lang/swift-t/pull/146) attempts to run the app (upon failure) in a different MPI rank.

A simple [test](https://github.com/swift-lang/swift-t/pull/146/commits/e6c25203217c529ffa5f027afe6d3487c89400ef#diff-9179115453e8580302bd54d01f104423) is added, where an external app (an [infinite loop](https://github.com/swift-lang/swift-t/pull/146/commits/e6c25203217c529ffa5f027afe6d3487c89400ef#diff-48f9430b764392651b9bb69821437639) ) is [run in the background](https://github.com/swift-lang/swift-t/pull/146/commits/e6c25203217c529ffa5f027afe6d3487c89400ef#diff-11de74ee5bcac3764f8d4498d588d1ca), and turbine attempts to kill it twice. This works fine the first time, but when attempting to kill it again, it either fails (if no retries are allowed), or retries `TURBINE_APP_RETRIES` times (in different ranks) and quits upon failure.

Another simple [test](https://github.com/zo0z/swift-t/blob/f90563ad38eafd179325d6b8a090cc46b897ac84/turbine/code/tests/retry_ranks2.sh) creates a file, then attempts to delete it twice. Creation and deletion both work in the first time, and the second deletion attempt would retry on different MPI ranks until reaching `TURBINE_APP_RETRIES` times , at which point the script exits.

**Comment by zo0z** [comment]
Upon a closer look, an app is delayed either:

- before it is launched by setting, `TURBINE_APP_DELAY` ( [new feature](https://github.com/swift-lang/swift-t/commit/469494778325e6617b964f9853e1d4bfe1871d9e) ). This is via the `app_delay` function by `round($app_delay_time * 1000.0 * rand())`

- between retries when it fails the first time and until it either succeeds or `TURBINE_APP_RETRIES` are reached. In [this recent commit](https://github.com/swift-lang/swift-t/pull/146/commits/f90563ad38eafd179325d6b8a090cc46b897ac84#diff-3969a890df7b4efc7409da9cb4468d74)  This is achieved via the `app_delay_retries`, by ` $app_backoff * pow(2, $tries) * rand()`

I think this behavior is sensible in both cases. Any ideas or comments?

**Comment by jmjwozniak** [comment]
I would like to merge this.  Can you add some user control to enable or disable this feature, say by an environment variable TURBINE_APP_REPUT ?  Re-put means the app call is retried with another ADLB_Put.  Other name suggestions or controls are welcome.  I think this feature should be disabled by default because it would be unexpected, but well documented and easy to enable.

**Comment by zo0z** [comment]
You are right, will follow the convention more closely. 

If I'm following correctly, the behavior could be:
`TURBINE_APP_RETRIES=n` ==> A failing app is retried on the same rank for `n` times (old behaviour)
`TURBINE_APP_REPUT`==>  If this was set to 1, then the `n` retries are put to different ranks.

However, maybe it is easier (from a user perspective) to set the retry behavior via single parameter.. As in:
`TURBINE_APP_RETRY_LOCAL=n` ==> A failing app is retried on the same rank for `n` times (old behavior)
`TURBINE_APP_RETRY_REPUT=n` ==> A failing app is retried on other ranks (besides its own) for `n` times (this pull request)

Would you have a preference among the 2?

**Comment by jmjwozniak** [comment]
I like your second idea- it is neatly categorized.

**Comment by zo0z** [comment]
Great! The latest pull request would now retry an app either locally or on a new rank, depending on which `TURBINE_APP_RETRY_LOCAL=n` or `TURBINE_APP_RETRY_REPUT=n` is set.

If both directives were specified, only the local retries will be done. Not sure if the user should get a warning (in the log) in this case?

**Comment by zo0z** [comment]
Pull request merged [here](https://github.com/swift-lang/swift-t/pull/146), so closing this ticket
