### ISSUE TITLE
LSF module

### ISSUE THREAD

**Issue by gounley** [swift-lang/swift-t#164]
Following up on #147 , Summit introduces a quirk in LSF, it doesn't support input redirection.  

Depending on whether broad LSF support is required, it seems like we could either:
1. Simply remove the redirection (line 51 in turbine-lsf-run.zsh)
2. Add a Summit flag a la Titan

**Comment by jmjwozniak** [comment]
Which version of Swift/T is this?  I am running on Summit without this issue.

**Comment by gounley** [comment]
I was running cca297a4d078c1c6043646137e0df8854112709a.

**Comment by jmjwozniak** [comment]
This was fixed in git.
