### ISSUE TITLE
M4 lsf template

### ISSUE THREAD

**Issue by gounley** [swift-lang/swift-t#176]
Looks like some git merge conflict markers got into the M4 template for LSF in commit 918bd803667921de0f856c10b60c8b065105bb7f: see  https://github.com/swift-lang/swift-t/commit/918bd803667921de0f856c10b60c8b065105bb7f#diff-996941417e62d7a6f3f37363b8244869

This is giving an error of "env: parameter not set" when turbine-lsf-run.zsh is run on Summit. Seems like an easy fix, but right way to resolve the merge conflict isn't obvious to me, as my attempts simply return the same error.

**Comment by jmjwozniak** [comment]
Oops.  Unfortunately I am on vacation without my keys until Wednesday.  Does the public installation work?

**Comment by gounley** [comment]
Ah ok, thanks for the quick reply. There's no rush; I can find a workaround. Enjoy your vacation :)

Ended up doing this because public installs were giving me trouble: CUDA doesn't load correctly in the old March install due to the compiler upgrade last month and, so far as I can tell, the executable in the May install appears to be missing.

**Comment by jmjwozniak** [comment]
Ok, try the fix above: cf8364c

**Comment by jmjwozniak** [comment]
Did this work?

**Comment by gounley** [comment]
No, still getting an error from 'env' not being found. This, I guess, isn't surprising as recent commits replaced env. I didn't have time to go through it, so I just rolled back to f12045594bc0cc6a613f5137bbb042878e104d28 and things seemed ok.

**Comment by jmjwozniak** [comment]
Ok, I am starting some runs on Summit today so I will get this tested...

**Comment by jmjwozniak** [comment]
Pretty sure this is fixed now (much later than expected due to Summit configuration issues).
