### ISSUE TITLE
MPIX_Comm_launch fails with OpenMPI

### ISSUE THREAD

**Issue by ncollier** [swift-lang/swift-t#181]
The arguments to mpiexec created in MPIX_Comm_launch (`swift-t/turbine/code/src/tcl/launch/MPIX_Comm_launch.c`) are not recognized by OpenMPI's mpiexec. This was tested with OpenMPI (4.0.1). 

In particular, the following are not recognized:

1.` -hosts`
2. `-launcher`
3. `env`

In openmpi `-hosts` is `-host` and `env` is a list of `-x VAR=VALUE`, one for each env var.  Not sure what the equivalent to launcher is. Docs have:

```
-mca plm_rsh_agent
Specifies the agent that will launch executables on remote nodes. The value is a colon-delimited list of agents, in order of precedence.
Default: ssh : rsh
```
and also

```
-launch-agent|--launch-agent <arg0>  
                         Command used to start processes on remote nodes
                         (default: orted)
```

**Comment by jmjwozniak** [comment]
OpenMPI cannot do recursive mpiexec, even in a simple shell script.

**Comment by jmjwozniak** [comment]
```
$ mpiexec -n 1 mpiexec

Open MPI does not support recursive calls of mpiexec
```
