### ISSUE TITLE
Run build- lb.sh report errors

### ISSUE THREAD

**Issue by jackycjw** [swift-lang/swift-t#187]
Error when i running "build- lb.sh" script

`mkdir: created directory 'lib'
  LINK		lib/libadlb.so
/usr/bin/ld: /root/mpich-install/lib/libmpich.a(initthread.o): relocation R_X86_64_TPOFF32 against symbol `MPIR_Thread' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /root/mpich-install/lib/libmpich.a(ch3u_rma_sync.o): relocation R_X86_64_PC32 against symbol `MPIDI_CH3I_progress_completion_count' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:227: recipe for target 'lib/libadlb.so' failed
make: *** [lib/libadlb.so] Error 1
`
i am a novice at these things. can anyone can help me

**Comment by jmjwozniak** [comment]
Hi
  It looks like your MPI installation does not have a shared library.  You need libmpich.so .  I recommend installing MPI via the package for your OS.  (I was able to reproduce this error by removing my libmpi.so .)
  Justin


--

Justin M Wozniak


________________________________

**Comment by jackycjw** [comment]
Hello, I have another proble。I've installed swift-t，and Successfully executed the script ('spack install stc ^turbine+python+r')。
But when I execute a script(swift-t python-f.swift), I report an error again

Scripts are two files
python-f.swift:
`import python;
x = 2; y = 3;
z = python("import F",
           "F.f(%i,%i)" % (x,y));
trace(z);
`
F.py:
`import python;
x = 2; y = 3;
z = python("import F",
           "F.f(%i,%i)" % (x,y));
trace(z);
`

Here is the error message
"Turbine not compiled with Python support

Swift: Error in Python code!

Swift: Aborting MPI job...
ADLB: ADLB_Abort(1) calling MPI_Abort(1)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0"

I don't know where the problem is...
Thanks for your help @jmjwozniak

**Comment by jozik** [comment]
Could you have previously installed a non-Python enabled Swift/T and the swift-t is pointing to that?

**Comment by jackycjw** [comment]
thanks! @jozik  @jmjwozniak
