### ISSUE TITLE
Anaconda package for Linux

### ISSUE THREAD

**Issue by j-woz** [swift-lang/swift-t#200]

**Comment by j-woz** [comment]
The build scripts are here: git@github.com:j-woz/lightsource2-recipes.git  recipes-tag/swift-t

**Comment by jozik** [comment]
Sub-tasks also include:

- being able to use yaml fragments when specifying inclusions of bits (e.g., R-enabled)
- being able to use wildcards or version ranges so that conda doesn't e.g., go from Python 3.9.16 to 3.9.0 on install
- automated build farm (gitlab, condo nodes?)

**Comment by j-woz** [comment]
Done, including sub-tasks, for Python 3.8 - 3.11.  Tested in GCE Jenkins w/w/o R.
