### ISSUE TITLE
Configurable placement policies for ADLB data

### ISSUE THREAD

**Issue by jmjwozniak** [swift-lang/swift-t#3]
_From @GoogleCodeExporter on April 22, 2015 19:5_

```
Maybe we should have the option to configure (either globally or per-variable) 
the policy for placing data.  E.g. on the nearest server or randomly.

Thoughts, Justin?
```

Original issue reported on code.google.com by `tim.g.ar...@gmail.com` on 17 Apr 2015 at 3:23

_Copied from original issue: jmjwozniak/exm-issues#794_

**Comment by jmjwozniak** [comment]
_From @GoogleCodeExporter on April 22, 2015 19:5_

```
Sounds good- I think we should start with some low-level primitives like what 
@location offers and work up from there to @heavy, @heavy=10*MB, etc.  

A related note is memory availability on servers but maybe that should be 
another issue? 
```

Original comment by `wozniak....@gmail.com` on 18 Apr 2015 at 2:06

**Comment by jmjwozniak** [comment]
_From @GoogleCodeExporter on April 22, 2015 19:5_

```
Yes I think the memory issue is pretty separate.

I was also wondering if we should switch to random placement by default - it 
seems like worst-case behavior is better with that since load imbalance isn't 
as likely to get as bad (I think I actually switched it to nearest-server at 
one time, which may have been misguided).
```

Original comment by `tim.g.ar...@gmail.com` on 20 Apr 2015 at 2:55

**Comment by jmjwozniak** [comment]
_From @GoogleCodeExporter on April 22, 2015 19:5_

```
Sure.
```

Original comment by `wozniak....@gmail.com` on 21 Apr 2015 at 8:34

**Comment by timarmstrong** [comment]
I checked in some initial work on this and changed the default to random placement.

There isn't yet a way to specify this per-item.

**Comment by timarmstrong** [comment]
This is now implemented at ADLB level and turbine level for the data create calls.  You can add a keyword arg to the create call, e.g.
[ adlb::create integer placement random ]
[ adlb::create integer 1 placement local ]

This isn't exposed yet at Swift/T level
